package.json
src/components/MediaObject.tsx
src/constants/strings.ts
src/content-components/index.ts
src/context/NFTDataProvider.tsx
src/nft-full/AuctionInfo.tsx
src/nft-full/BidHistory.tsx
src/nft-full/CreatorEquity.tsx
src/nft-full/MediaFull.tsx
src/nft-full/MediaInfo.tsx
src/nft-preview/MediaThumbnail.tsx
src/nft-preview/MediaThumbnailWrapper.tsx
src/nft-preview/PricingComponent.tsx
yarn.lock

Upgrade components to match latest nft-hooks dependency updates

Updating components and metadata to match nft-hooks dependencies

---

src/constants/strings.ts
src/content-components/Audio.tsx
src/nft-full/BidHistory.tsx
src/nft-full/NFTFullPage.tsx
src/nft-full/PlaceOfferButton.tsx
src/stories/NFTFull.stories.tsx

fixing bid button styling and text, fixing sorting for auction auction

---

jest.config.js
package.json
src/components/AddressView.tsx
src/constants/strings.ts
src/nft-full/AuctionInfo.tsx
src/nft-full/BidHistory.tsx
src/nft-full/NFTFullPage.tsx
src/stories/NFTFull.stories.tsx
tests/components/AuctionInfo.test.tsx
tests/components/BidHistory.test.tsx
tests/components/fetchMock.ts
tests/components/mock-data/download-mock-data.script.ts
tests/components/mock-data/test_no_auction.json
tests/components/mock-data/test_perpetual_bids.json
tests/components/mock-data/test_perpetual_bids_w_ask_no_bids.json
tests/components/mock-data/test_reserve_active_auction.json
tests/components/mock-data/test_reserve_auction_complete.json
tests/components/mock-data/test_reserve_pending_auction.json
tsconfig.json
yarn.lock

Fix logic for perpetual auctions and reserve auctions in full info container.

Auction information shows "List price" instead of "Highest bid" for perpetual auctions

---

src/nft-full/BidHistory.tsx
src/nft-full/NFTFullPage.tsx
tests/components/AuctionInfo.test.tsx
tests/components/BidHistory.test.tsx

Remove perpetual bids history when flag to remove perpetual bids is passed in

Remove perpetual bids history when flag passed in

---

package.json
src/constants/theme.ts
src/nft-full/AuctionInfo.tsx
src/nft-full/BidHistory.tsx
src/nft-preview/PricingComponent.tsx
src/utils/PricingString.tsx
yarn.lock

Moves pricing calculations to a common component

Move pricing info common component

---

package.json
src/constants/style.ts
src/utils/PricingString.tsx

Fix server-side rendering not requiring navigator.locale and set default.

Fix server rendering

---

src/auction-house/AuctionHouseList.tsx
src/nft-full/AuctionInfo.tsx

Ending auctions threw an exception for showPerpetual={true} auctionInformation endpoints.

Fix auction ending bug

---

package.json
src/components/MediaObject.tsx
src/stories/NFTFull.stories.tsx

This suggests mime types for media / animation urls allowing fallbacks as needed.
Todo: handle content-type correctly for media (animations that are svgs and html).

Fix artblocks rendering

---

src/constants/theme.ts

Change theme card bg to white to make display more consistent w/ black text.

changing default theme bg to white

---

package.json
src/components/MediaObject.tsx
src/constants/strings.ts
src/constants/style.ts
src/content-components/Audio.tsx
src/content-components/Video.tsx
src/nft-full/BidHistory.tsx
src/nft-full/CreatorEquity.tsx
src/nft-full/InfoContainer.tsx
src/nft-full/MediaFull.tsx
src/nft-full/MediaInfo.tsx
src/nft-full/NFTFullPage.tsx
src/nft-preview/MediaThumbnail.tsx
src/nft-preview/MediaThumbnailWrapper.tsx
src/utils/useA11yIdPrefix.ts
yarn.lock

1. fix video rendering in safari
2. fix audio rendering in safari
3. add aria- labelling and active code to play buttons
4. fix keyboard navigation for aria video player
5. fix keyboard navigation for audio player
6. add <time> html tag with formatting
7. add dl to authorship history
8. add ol to history

Improve rendering safari and a11y improvements

---

package.json
src/context/MediaConfiguration.tsx
src/nft-full/MediaFull.tsx

Fix props for renderer prior to full release

Fix props prior release

---

src/components/MediaObject.tsx
src/content-components/Audio.tsx
src/context/MediaConfiguration.tsx
src/context/useMediaContext.ts

This adds audio waveforms that are pusedorandom based off the audio filename instead of the same every time.

Make Audio Waveforms base puesdo-random based off content URI

---

src/components/MediaObject.tsx
src/content-components/Image.tsx
src/content-components/RendererConfig.ts
src/content-components/Video.tsx
src/stories/NFTFull.stories.tsx

1. adding in video rendering error fallback
2. adjusting interactive rendering threshold
3. adding theme data (prep for #49)

[components] rendering updates

---

package.json
src/nft-full/BidHistory.tsx
src/nft-full/PlaceOfferButton.tsx
yarn.lock

Adding hosted bid flow for any NFT auctions

[bid button] adding any nft hosted flow to bid buttons

---

src/constants/strings.ts
src/constants/style.ts
src/constants/svg-icons.ts
src/constants/theme.ts
src/nft-full/BidHistory.tsx

Adding some new classes and ability for transactions to link to new pages

Adding css target classes bid history

---

src/components/CountdownDisplay.tsx
tests/components/CountdownDisplay.test.tsx

Fixing negative countdown and adding regression tests

Fixing countdown

---

src/constants/strings.ts
src/constants/style.ts
src/nft-full/CreatorEquity.tsx
src/nft-full/ProofAuthenticity.tsx

Adding curator equity text and description

Adding curator equity text

---

package.json
src/components/CountdownDisplay.tsx
src/constants/strings.ts
src/nft-full/AuctionInfo.tsx
tests/components/AuctionInfo.test.tsx
tests/components/BidHistory.test.tsx
tests/components/CountdownDisplay.test.tsx

Add auction duration info box to nft full view

---

src/content-components/HTML.tsx
src/content-components/Model.tsx
src/content-components/Text.tsx
src/content-components/Unknown.tsx

1. don't allow text rendering of application/html
2. move fallback from invalid to fallback status
3. don't update object state for 3d model rendering to fix next hydration

Updating rendering preferences to fix zoraco rendering

---

CHANGELOG
src/components/AddressView.tsx
src/constants/theme.ts

adding flags for zora username resolution and ens

---

src/constants/style.ts
src/nft-full/AuctionInfo.tsx
src/utils/PricingString.tsx

primarily wrapping text in div and pulling h4 header into layout composition for bid, bidder etc.

refactored auctioninfo layout, 

---

src/components/AddressView.tsx
src/components/Button.tsx
src/components/MediaObject.tsx
src/content-components/MediaLoader.tsx
src/context/useMediaContext.ts
src/nft-full/AuctionInfo.tsx
src/nft-full/BidHistory.tsx
src/nft-full/CreatorEquity.tsx
src/nft-full/InfoContainer.tsx
src/nft-full/MediaFull.tsx
src/nft-full/MediaInfo.tsx
src/nft-full/NFTFullPage.tsx
src/nft-full/PlaceOfferButton.tsx
src/nft-full/ProofAuthenticity.tsx
src/nft-preview/MediaThumbnail.tsx
src/nft-preview/MediaThumbnailWrapper.tsx
src/nft-preview/NFTPreview.tsx
src/nft-preview/PricingComponent.tsx
src/nft-proposal/NFTProposal.tsx
src/nft-proposal/ProposalActionList.tsx
src/nft-proposal/ProposalMediaDisplay.tsx
src/nft-proposal/ProposalUserView.tsx
src/utils/StyleTypes.ts

Updates styles and components and forwards classNames to components
Fixes #79

Forward className prop to components

---

CHANGELOG
package.json
src/components/AddressView.tsx
src/constants/theme.ts
src/content-components/LoadingError.tsx
src/nft-full/NFTProperties.tsx
yarn.lock

Shot to make indexer data a priority and added a handler to convert attributes in object form to an array.

Properties component in nft full

---

src/nft-full/AuctionInfo.tsx

https://github.com/ourzora/nft-components/commit/2bcb55455752203e88bd33900bf2095457993352#r59877027

[fix] remove extra wrapping div around auction info

---

src/content-components/Audio.tsx
src/content-components/Video.tsx

This fixes the video controls arguments passing.

Audio controls and video controls fix update

---

src/nft-full/AuctionInfo.tsx
src/nft-full/BidHistory.tsx

Fixes an issue where auction info was incorrectly returning a fragment instead of reserve auction info when perpetual ask data was not present.

Fixes issue with auction info

---

src/nft-proposal/ProposalActionList.tsx
src/nft-proposal/ProposalMediaDisplay.tsx

I know these components are marked as depreciated but we will need to use them until we integrate the new ZoraV3 reserve modules. These changes update the auction proposal components to use the new NFT hooks data structure.

Fixes auction proposal

---

src/nft-full/AuctionInfo.tsx
src/nft-full/CollectionTag.tsx

Changes auction info to pull data for any fixed price like instead of only ZoraV3.
Fixes issues with collection tag not getting collection image properly.

Artiva fixes

---

package.json
src/constants/strings.ts
src/nft-full/BidHistory.tsx
src/nft-preview/PricingComponent.tsx
src/stories/NFTFull.stories.tsx
src/stories/NFTPreview.stories.tsx
src/utils/PricingString.tsx
yarn.lock

* Fix events sort order
* Fix currency rendering for missing data
* Fix history list
* Remove unused nodejs packages

[wip] hooks update fixes

---

package.json
src/constants/strings.ts
src/nft-full/BidHistory.tsx
src/nft-full/NFTProperties.tsx
yarn.lock

* Add event listing for bid history
* Cleanup text and styles

Update auction history components
